# Official Nginx image
FROM nginx:alpine

# Remove default config
RUN rm /etc/nginx/conf.d/default.conf

# Copy our custom config
COPY proxy/nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80